#!/bin/bash

HOME=/home/steam

YEAR=$(date +"%Y")
MOUTH=$(date +"%m")
DAY=$(date +"%d")
HOUR=$(date +"%H")
DATE=${YEAR}${MOUTH}${DAY}${HOUR}

pushd ${HOME}
mkdir -p /backup/${YEAR}/${MOUTH}/${DAY}
mkdir -p /backup/temp/save
cp -rf Steam/steamapps/common/PalServer/Pal/Saved/SaveGames/*/*/* /backup/temp/save
cp -rf Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini /backup/temp
pushd /backup/temp
tar cvf /backup/${YEAR}/${MOUTH}/${DAY}/palworld-backup.${DATE}.tar.gz *
popd
rm -rf /backup/temp
popd
